
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const AboutIntroSection: typeof import("../components/about-intro-section")['default']
export const AdvantagesSection: typeof import("../components/advantages-section")['default']
export const BusinessTypesSection: typeof import("../components/business-types-section")['default']
export const ContactCtaSection: typeof import("../components/contact-cta-section")['default']
export const Footer: typeof import("../components/footer")['default']
export const HeroSection: typeof import("../components/hero-section")['default']
export const IndustriesSection: typeof import("../components/industries-section")['default']
export const Navbar: typeof import("../components/navbar")['default']
export const NewsSection: typeof import("../components/news-section")['default']
export const PageBanner: typeof import("../components/page-banner")['default']
export const SectionDivider: typeof import("../components/section-divider")['default']
export const SectionTitle: typeof import("../components/section-title")['default']
export const ServicesSection: typeof import("../components/services-section")['default']
export const SolutionsEntrySection: typeof import("../components/solutions-entry-section")['default']
export const StatsSection: typeof import("../components/stats-section")['default']
export const TechSection: typeof import("../components/tech-section")['default']
export const ThemeProvider: typeof import("../components/theme-provider")['default']
export const UiAccordion: typeof import("../components/ui/accordion")['default']
export const UiAlertDialog: typeof import("../components/ui/alert-dialog")['default']
export const UiAlert: typeof import("../components/ui/alert")['default']
export const UiAspectRatio: typeof import("../components/ui/aspect-ratio")['default']
export const UiAvatar: typeof import("../components/ui/avatar")['default']
export const UiBadge: typeof import("../components/ui/badge")['default']
export const UiBreadcrumb: typeof import("../components/ui/breadcrumb")['default']
export const UiButton: typeof import("../components/ui/button")['default']
export const UiCalendar: typeof import("../components/ui/calendar")['default']
export const UiCard: typeof import("../components/ui/card")['default']
export const UiCarousel: typeof import("../components/ui/carousel")['default']
export const UiChart: typeof import("../components/ui/chart")['default']
export const UiCheckbox: typeof import("../components/ui/checkbox")['default']
export const UiCollapsible: typeof import("../components/ui/collapsible")['default']
export const UiCommand: typeof import("../components/ui/command")['default']
export const UiContextMenu: typeof import("../components/ui/context-menu")['default']
export const UiDialog: typeof import("../components/ui/dialog")['default']
export const UiDrawer: typeof import("../components/ui/drawer")['default']
export const UiDropdownMenu: typeof import("../components/ui/dropdown-menu")['default']
export const UiForm: typeof import("../components/ui/form")['default']
export const UiHoverCard: typeof import("../components/ui/hover-card")['default']
export const UiInputOtp: typeof import("../components/ui/input-otp")['default']
export const UiInput: typeof import("../components/ui/input")['default']
export const UiLabel: typeof import("../components/ui/label")['default']
export const UiMenubar: typeof import("../components/ui/menubar")['default']
export const UiNavigationMenu: typeof import("../components/ui/navigation-menu")['default']
export const UiPagination: typeof import("../components/ui/pagination")['default']
export const UiPopover: typeof import("../components/ui/popover")['default']
export const UiProgress: typeof import("../components/ui/progress")['default']
export const UiRadioGroup: typeof import("../components/ui/radio-group")['default']
export const UiResizable: typeof import("../components/ui/resizable")['default']
export const UiScrollArea: typeof import("../components/ui/scroll-area")['default']
export const UiSelect: typeof import("../components/ui/select")['default']
export const UiSeparator: typeof import("../components/ui/separator")['default']
export const UiSheet: typeof import("../components/ui/sheet")['default']
export const UiSidebar: typeof import("../components/ui/sidebar")['default']
export const UiSkeleton: typeof import("../components/ui/skeleton")['default']
export const UiSlider: typeof import("../components/ui/slider")['default']
export const UiSonner: typeof import("../components/ui/sonner")['default']
export const UiSwitch: typeof import("../components/ui/switch")['default']
export const UiTable: typeof import("../components/ui/table")['default']
export const UiTabs: typeof import("../components/ui/tabs")['default']
export const UiTextarea: typeof import("../components/ui/textarea")['default']
export const UiToast: typeof import("../components/ui/toast")['default']
export const UiToaster: typeof import("../components/ui/toaster")['default']
export const UiToggleGroup: typeof import("../components/ui/toggle-group")['default']
export const UiToggle: typeof import("../components/ui/toggle")['default']
export const UiTooltip: typeof import("../components/ui/tooltip")['default']
export const UiUseMobile: typeof import("../components/ui/use-mobile")['default']
export const UiUseToast: typeof import("../components/ui/use-toast")['default']
export const WarehouseNetworkSection: typeof import("../components/warehouse-network-section")['default']
export const NuxtWelcome: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtAnnouncer: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']
export const NuxtImg: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']
export const NoScript: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyAboutIntroSection: LazyComponent<typeof import("../components/about-intro-section")['default']>
export const LazyAdvantagesSection: LazyComponent<typeof import("../components/advantages-section")['default']>
export const LazyBusinessTypesSection: LazyComponent<typeof import("../components/business-types-section")['default']>
export const LazyContactCtaSection: LazyComponent<typeof import("../components/contact-cta-section")['default']>
export const LazyFooter: LazyComponent<typeof import("../components/footer")['default']>
export const LazyHeroSection: LazyComponent<typeof import("../components/hero-section")['default']>
export const LazyIndustriesSection: LazyComponent<typeof import("../components/industries-section")['default']>
export const LazyNavbar: LazyComponent<typeof import("../components/navbar")['default']>
export const LazyNewsSection: LazyComponent<typeof import("../components/news-section")['default']>
export const LazyPageBanner: LazyComponent<typeof import("../components/page-banner")['default']>
export const LazySectionDivider: LazyComponent<typeof import("../components/section-divider")['default']>
export const LazySectionTitle: LazyComponent<typeof import("../components/section-title")['default']>
export const LazyServicesSection: LazyComponent<typeof import("../components/services-section")['default']>
export const LazySolutionsEntrySection: LazyComponent<typeof import("../components/solutions-entry-section")['default']>
export const LazyStatsSection: LazyComponent<typeof import("../components/stats-section")['default']>
export const LazyTechSection: LazyComponent<typeof import("../components/tech-section")['default']>
export const LazyThemeProvider: LazyComponent<typeof import("../components/theme-provider")['default']>
export const LazyUiAccordion: LazyComponent<typeof import("../components/ui/accordion")['default']>
export const LazyUiAlertDialog: LazyComponent<typeof import("../components/ui/alert-dialog")['default']>
export const LazyUiAlert: LazyComponent<typeof import("../components/ui/alert")['default']>
export const LazyUiAspectRatio: LazyComponent<typeof import("../components/ui/aspect-ratio")['default']>
export const LazyUiAvatar: LazyComponent<typeof import("../components/ui/avatar")['default']>
export const LazyUiBadge: LazyComponent<typeof import("../components/ui/badge")['default']>
export const LazyUiBreadcrumb: LazyComponent<typeof import("../components/ui/breadcrumb")['default']>
export const LazyUiButton: LazyComponent<typeof import("../components/ui/button")['default']>
export const LazyUiCalendar: LazyComponent<typeof import("../components/ui/calendar")['default']>
export const LazyUiCard: LazyComponent<typeof import("../components/ui/card")['default']>
export const LazyUiCarousel: LazyComponent<typeof import("../components/ui/carousel")['default']>
export const LazyUiChart: LazyComponent<typeof import("../components/ui/chart")['default']>
export const LazyUiCheckbox: LazyComponent<typeof import("../components/ui/checkbox")['default']>
export const LazyUiCollapsible: LazyComponent<typeof import("../components/ui/collapsible")['default']>
export const LazyUiCommand: LazyComponent<typeof import("../components/ui/command")['default']>
export const LazyUiContextMenu: LazyComponent<typeof import("../components/ui/context-menu")['default']>
export const LazyUiDialog: LazyComponent<typeof import("../components/ui/dialog")['default']>
export const LazyUiDrawer: LazyComponent<typeof import("../components/ui/drawer")['default']>
export const LazyUiDropdownMenu: LazyComponent<typeof import("../components/ui/dropdown-menu")['default']>
export const LazyUiForm: LazyComponent<typeof import("../components/ui/form")['default']>
export const LazyUiHoverCard: LazyComponent<typeof import("../components/ui/hover-card")['default']>
export const LazyUiInputOtp: LazyComponent<typeof import("../components/ui/input-otp")['default']>
export const LazyUiInput: LazyComponent<typeof import("../components/ui/input")['default']>
export const LazyUiLabel: LazyComponent<typeof import("../components/ui/label")['default']>
export const LazyUiMenubar: LazyComponent<typeof import("../components/ui/menubar")['default']>
export const LazyUiNavigationMenu: LazyComponent<typeof import("../components/ui/navigation-menu")['default']>
export const LazyUiPagination: LazyComponent<typeof import("../components/ui/pagination")['default']>
export const LazyUiPopover: LazyComponent<typeof import("../components/ui/popover")['default']>
export const LazyUiProgress: LazyComponent<typeof import("../components/ui/progress")['default']>
export const LazyUiRadioGroup: LazyComponent<typeof import("../components/ui/radio-group")['default']>
export const LazyUiResizable: LazyComponent<typeof import("../components/ui/resizable")['default']>
export const LazyUiScrollArea: LazyComponent<typeof import("../components/ui/scroll-area")['default']>
export const LazyUiSelect: LazyComponent<typeof import("../components/ui/select")['default']>
export const LazyUiSeparator: LazyComponent<typeof import("../components/ui/separator")['default']>
export const LazyUiSheet: LazyComponent<typeof import("../components/ui/sheet")['default']>
export const LazyUiSidebar: LazyComponent<typeof import("../components/ui/sidebar")['default']>
export const LazyUiSkeleton: LazyComponent<typeof import("../components/ui/skeleton")['default']>
export const LazyUiSlider: LazyComponent<typeof import("../components/ui/slider")['default']>
export const LazyUiSonner: LazyComponent<typeof import("../components/ui/sonner")['default']>
export const LazyUiSwitch: LazyComponent<typeof import("../components/ui/switch")['default']>
export const LazyUiTable: LazyComponent<typeof import("../components/ui/table")['default']>
export const LazyUiTabs: LazyComponent<typeof import("../components/ui/tabs")['default']>
export const LazyUiTextarea: LazyComponent<typeof import("../components/ui/textarea")['default']>
export const LazyUiToast: LazyComponent<typeof import("../components/ui/toast")['default']>
export const LazyUiToaster: LazyComponent<typeof import("../components/ui/toaster")['default']>
export const LazyUiToggleGroup: LazyComponent<typeof import("../components/ui/toggle-group")['default']>
export const LazyUiToggle: LazyComponent<typeof import("../components/ui/toggle")['default']>
export const LazyUiTooltip: LazyComponent<typeof import("../components/ui/tooltip")['default']>
export const LazyUiUseMobile: LazyComponent<typeof import("../components/ui/use-mobile")['default']>
export const LazyUiUseToast: LazyComponent<typeof import("../components/ui/use-toast")['default']>
export const LazyWarehouseNetworkSection: LazyComponent<typeof import("../components/warehouse-network-section")['default']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtAnnouncer: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/pages/runtime/page-placeholder")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/.pnpm/nuxt@4.4.2_@babel+core@7.29.0_@babel+plugin-syntax-jsx@7.28.6_@babel+core@7.29.0__@emna_44e245e2c77353c5eeedf744110a6511/node_modules/nuxt/dist/app/components/nuxt-island")['default']>

export const componentNames: string[]
